# Goal (Final coordinates and orientation the turtle must reach)
float64 x
float64 y
float64 theta
---
# Result (Indicates successful completion of the action)
bool success
---
# Feedback (Continuous remaining distance to reach the positional goal)
float64 distance_remaining
